name: 'Build master'

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.ini'
      - '**.css'
      - '**.js'
      - '**.html'
      - '**.json'
      - '**.png'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 'Get ${{ env.project}} git info'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          git fetch --prune --unshallow
          echo "GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Clean gradle
        run: ./gradlew clean --no-daemon --max-workers 1
      - name: Validate no assets
        run: test ! -d ./src/generated
      - name: Generate assets
        run: ./gradlew runData --no-daemon --max-workers 1
      - name: Validate assets
        run: test -d ./src/generated -a -f ./src/generated/resources/.cache/cache
      - name: Build with Gradle
        run: ./gradlew build --no-daemon --max-workers 1
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'va-${{ env.GIT_TAG }}-${{ env.GIT_HASH }}'
          path: ${{github.workspace}}/build/libs/*.jar
